### PR TITLE
use wagmi instead of web3react: Amazing improvement

### PR DESCRIPTION
**Pull request by iainnash**
Using new library backend

### CODE REVIEW

**Comment by jem-computer** [comment]
yessssss

**Comment by dblodorn** [comment]
Looks v-nice @iainnash

**Comment by jem-computer** [comment]
@iainnash is there anything blocking this from merging?

**Comment by iainnash** [comment]
I think I got the object returned wrong, just wanted to test some more.

**Comment by iainnash** [comment]
Should be good now, needed to add some more info to the compat object.

**Pull request merged**
